name: Build with CMake

on:
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  warmux:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq gettext rpm build-essential cmake dh-make autoconf-archive autoconf automake autotools-dev libxml2-dev libcurl4-openssl-dev libfribidi-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev libsdl2-gfx-dev libsdl2-dev libsdl2-net-dev
      - name: Clone warmux
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: Build warmux with CMake
        run: |
          cd trunk
          cmake .
          make -j4 VERBOSE=1
          sudo make install
